from tkinter import *
janela =  Tk()
janela.title("Empresa")
janela.iconbitmap('Icon.ico')
janela['bg']=('blue')
janela.geometry('500x400+50+20')
etiqueta=Label(janela,bg='blue', text='Olá Mundo',cursor='dot')
etiqueta.pack()
etiqueta1=Label(janela,height=10,width=20,bg='blue' ,text='Olá Mundo',cursor='dot')
etiqueta1.pack()
etiqueta2=Label(janela,height=10,width=40, fg='red',bg='blue', text ='Olá Mundo',relief="groove")
etiqueta2.pack()
janela.mainloop()
